--- #collect for triage
- hosts: '{{ node }}' 
  remote_user: root 
  gather_facts: no 
  become: yes
  become_method: sudo

  tasks:
    - import_tasks: tasks/setup.directory.yml
    - import_tasks: tasks/bridge.yml
    - import_tasks: tasks/arp.yml
    - import_tasks: tasks/evpn.mac.yml
    - import_tasks: tasks/evpn.route.yml
    - import_tasks: tasks/evpn.overlay.yml
