--- #collect for triage
- hosts: '{{ node }}'
  gather_facts: no 
  become: yes
  become_method: sudo

  - name: timestamp_start
    shell: '/bin/echo "the time is now " && /bin/date' 
    register: start_result
  - local_action: lineinfile line={{ start_result.stdout }} insertafter=EOF dest=/var/cumulus-collected/{{ inventory_hostname }}

  - name: print_bridge_table
    shell: '/sbin/bridge fdb show'
    register: bridge_result
  - local_action: lineinfile line={{ bridge_result.stdout }} insertafter=EOF dest=/var/cumulus-collected/{{ inventory_hostname }}
    tags: verify 

  - name: print_arp_table
    shell: '/sbin/ip neigh show'
    register: arp_result
  - local_action: lineinfile line={{ arp_result.stdout }} insertafter=EOF dest=/var/cumulus-collected/{{ inventory_hostname }}
    tags: verify 

  - name: print_evpn.mac_table
    shell: '/usr/bin/vtysh -c "show evpn mac vni 10032"'
    register: evpn.mac_result
  - local_action: lineinfile line={{ evpn.mac_result.stdout }} insertafter=EOF dest=/var/cumulus-collected/{{ inventory_hostname }}
    tags: verify 

  - name: print_evpn.route_table
    shell: '/usr/bin/vtysh -c "show bgp l2vpn evpn route"'
    register: evpn.route_result
  - local_action: lineinfile line={{ evpn.route_result.stdout }} insertafter=EOF dest=/var/cumulus-collected/{{ inventory_hostname }}
    tags: verify 

  - name: print_evpn.overlay_table
    shell: '/usr/bin/vtysh -c "show bgp l2vpn evpn overlay all"'
    register: evpn.overlay_result
  - local_action: lineinfile line={{ evpn.overlay_result.stdout }} insertafter=EOF dest=/var/cumulus-collected/{{ inventory_hostname }}
    tags: verify 

  - name: timestamp_end
    shell: '/bin/echo "the time is now " && /bin/date' 
    register: end_result
  - local_action: lineinfile line={{ end_result.stdout }} insertafter=EOF dest=/var/cumulus-collected/{{ inventory_hostname }}
