---
  - name: print_evpn.mac_table
    shell: '/usr/bin/vtysh -c "show evpn mac vni all"'
    register: evpn_mac_result
  - local_action: lineinfile line={{ evpn_mac_result.stdout }} insertafter=EOF dest=/var/cumulus-collected/{{ inventory_hostname }}/evpn_mac_result.stdout
    tags: verify

  - name: timestamp
    shell: '/bin/date'
    register: date_result
  - local_action: lineinfile line={{ date_result.stdout }} insertafter=EOF dest=/var/cumulus-collected/{{ inventory_hostname }}/evpn_mac_result.stdout
    tags: date
